/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStoresCreateRouteImport } from './routes/_authenticated/stores/create'
import { Route as AuthenticatedStoresStoreNumberIndexRouteImport } from './routes/_authenticated/stores/$storeNumber/index'
import { Route as AuthenticatedStoresStoreNumberEditRouteImport } from './routes/_authenticated/stores/$storeNumber/edit'
import { Route as AuthenticatedStoresStoreNumberBranchesCreateRouteImport } from './routes/_authenticated/stores/$storeNumber/branches/create'
import { Route as AuthenticatedStoresStoreNumberBranchesBranchNumberIndexRouteImport } from './routes/_authenticated/stores/$storeNumber/branches/$branchNumber/index'
import { Route as AuthenticatedStoresStoreNumberBranchesBranchNumberEditRouteImport } from './routes/_authenticated/stores/$storeNumber/branches/$branchNumber/edit'
import { Route as AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsCreateRouteImport } from './routes/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/create'
import { Route as AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberIndexRouteImport } from './routes/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/index'
import { Route as AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberEditRouteImport } from './routes/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoresCreateRoute =
  AuthenticatedStoresCreateRouteImport.update({
    id: '/stores/create',
    path: '/stores/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreNumberIndexRoute =
  AuthenticatedStoresStoreNumberIndexRouteImport.update({
    id: '/stores/$storeNumber/',
    path: '/stores/$storeNumber/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreNumberEditRoute =
  AuthenticatedStoresStoreNumberEditRouteImport.update({
    id: '/stores/$storeNumber/edit',
    path: '/stores/$storeNumber/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreNumberBranchesCreateRoute =
  AuthenticatedStoresStoreNumberBranchesCreateRouteImport.update({
    id: '/stores/$storeNumber/branches/create',
    path: '/stores/$storeNumber/branches/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreNumberBranchesBranchNumberIndexRoute =
  AuthenticatedStoresStoreNumberBranchesBranchNumberIndexRouteImport.update({
    id: '/stores/$storeNumber/branches/$branchNumber/',
    path: '/stores/$storeNumber/branches/$branchNumber/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreNumberBranchesBranchNumberEditRoute =
  AuthenticatedStoresStoreNumberBranchesBranchNumberEditRouteImport.update({
    id: '/stores/$storeNumber/branches/$branchNumber/edit',
    path: '/stores/$storeNumber/branches/$branchNumber/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsCreateRoute =
  AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsCreateRouteImport.update(
    {
      id: '/stores/$storeNumber/branches/$branchNumber/rooms/create',
      path: '/stores/$storeNumber/branches/$branchNumber/rooms/create',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberIndexRoute =
  AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberIndexRouteImport.update(
    {
      id: '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/',
      path: '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberEditRoute =
  AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberEditRouteImport.update(
    {
      id: '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit',
      path: '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/test': typeof AuthenticatedTestRoute
  '/admin/login': typeof AdminLoginRoute
  '/stores/create': typeof AuthenticatedStoresCreateRoute
  '/stores/$storeNumber/edit': typeof AuthenticatedStoresStoreNumberEditRoute
  '/stores/$storeNumber/': typeof AuthenticatedStoresStoreNumberIndexRoute
  '/stores/$storeNumber/branches/create': typeof AuthenticatedStoresStoreNumberBranchesCreateRoute
  '/stores/$storeNumber/branches/$branchNumber/edit': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberEditRoute
  '/stores/$storeNumber/branches/$branchNumber/': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberIndexRoute
  '/stores/$storeNumber/branches/$branchNumber/rooms/create': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsCreateRoute
  '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberEditRoute
  '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/test': typeof AuthenticatedTestRoute
  '/admin/login': typeof AdminLoginRoute
  '/stores/create': typeof AuthenticatedStoresCreateRoute
  '/stores/$storeNumber/edit': typeof AuthenticatedStoresStoreNumberEditRoute
  '/stores/$storeNumber': typeof AuthenticatedStoresStoreNumberIndexRoute
  '/stores/$storeNumber/branches/create': typeof AuthenticatedStoresStoreNumberBranchesCreateRoute
  '/stores/$storeNumber/branches/$branchNumber/edit': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberEditRoute
  '/stores/$storeNumber/branches/$branchNumber': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberIndexRoute
  '/stores/$storeNumber/branches/$branchNumber/rooms/create': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsCreateRoute
  '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberEditRoute
  '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/stores/create': typeof AuthenticatedStoresCreateRoute
  '/_authenticated/stores/$storeNumber/edit': typeof AuthenticatedStoresStoreNumberEditRoute
  '/_authenticated/stores/$storeNumber/': typeof AuthenticatedStoresStoreNumberIndexRoute
  '/_authenticated/stores/$storeNumber/branches/create': typeof AuthenticatedStoresStoreNumberBranchesCreateRoute
  '/_authenticated/stores/$storeNumber/branches/$branchNumber/edit': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberEditRoute
  '/_authenticated/stores/$storeNumber/branches/$branchNumber/': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberIndexRoute
  '/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/create': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsCreateRoute
  '/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberEditRoute
  '/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/': typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/test'
    | '/admin/login'
    | '/stores/create'
    | '/stores/$storeNumber/edit'
    | '/stores/$storeNumber/'
    | '/stores/$storeNumber/branches/create'
    | '/stores/$storeNumber/branches/$branchNumber/edit'
    | '/stores/$storeNumber/branches/$branchNumber/'
    | '/stores/$storeNumber/branches/$branchNumber/rooms/create'
    | '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit'
    | '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/test'
    | '/admin/login'
    | '/stores/create'
    | '/stores/$storeNumber/edit'
    | '/stores/$storeNumber'
    | '/stores/$storeNumber/branches/create'
    | '/stores/$storeNumber/branches/$branchNumber/edit'
    | '/stores/$storeNumber/branches/$branchNumber'
    | '/stores/$storeNumber/branches/$branchNumber/rooms/create'
    | '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit'
    | '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/_authenticated/dashboard'
    | '/_authenticated/test'
    | '/admin/login'
    | '/_authenticated/stores/create'
    | '/_authenticated/stores/$storeNumber/edit'
    | '/_authenticated/stores/$storeNumber/'
    | '/_authenticated/stores/$storeNumber/branches/create'
    | '/_authenticated/stores/$storeNumber/branches/$branchNumber/edit'
    | '/_authenticated/stores/$storeNumber/branches/$branchNumber/'
    | '/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/create'
    | '/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit'
    | '/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/create': {
      id: '/_authenticated/stores/create'
      path: '/stores/create'
      fullPath: '/stores/create'
      preLoaderRoute: typeof AuthenticatedStoresCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeNumber/': {
      id: '/_authenticated/stores/$storeNumber/'
      path: '/stores/$storeNumber'
      fullPath: '/stores/$storeNumber/'
      preLoaderRoute: typeof AuthenticatedStoresStoreNumberIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeNumber/edit': {
      id: '/_authenticated/stores/$storeNumber/edit'
      path: '/stores/$storeNumber/edit'
      fullPath: '/stores/$storeNumber/edit'
      preLoaderRoute: typeof AuthenticatedStoresStoreNumberEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeNumber/branches/create': {
      id: '/_authenticated/stores/$storeNumber/branches/create'
      path: '/stores/$storeNumber/branches/create'
      fullPath: '/stores/$storeNumber/branches/create'
      preLoaderRoute: typeof AuthenticatedStoresStoreNumberBranchesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeNumber/branches/$branchNumber/': {
      id: '/_authenticated/stores/$storeNumber/branches/$branchNumber/'
      path: '/stores/$storeNumber/branches/$branchNumber'
      fullPath: '/stores/$storeNumber/branches/$branchNumber/'
      preLoaderRoute: typeof AuthenticatedStoresStoreNumberBranchesBranchNumberIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeNumber/branches/$branchNumber/edit': {
      id: '/_authenticated/stores/$storeNumber/branches/$branchNumber/edit'
      path: '/stores/$storeNumber/branches/$branchNumber/edit'
      fullPath: '/stores/$storeNumber/branches/$branchNumber/edit'
      preLoaderRoute: typeof AuthenticatedStoresStoreNumberBranchesBranchNumberEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/create': {
      id: '/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/create'
      path: '/stores/$storeNumber/branches/$branchNumber/rooms/create'
      fullPath: '/stores/$storeNumber/branches/$branchNumber/rooms/create'
      preLoaderRoute: typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/': {
      id: '/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/'
      path: '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber'
      fullPath: '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/'
      preLoaderRoute: typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit': {
      id: '/_authenticated/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit'
      path: '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit'
      fullPath: '/stores/$storeNumber/branches/$branchNumber/rooms/$roomNumber/edit'
      preLoaderRoute: typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
  AuthenticatedStoresCreateRoute: typeof AuthenticatedStoresCreateRoute
  AuthenticatedStoresStoreNumberEditRoute: typeof AuthenticatedStoresStoreNumberEditRoute
  AuthenticatedStoresStoreNumberIndexRoute: typeof AuthenticatedStoresStoreNumberIndexRoute
  AuthenticatedStoresStoreNumberBranchesCreateRoute: typeof AuthenticatedStoresStoreNumberBranchesCreateRoute
  AuthenticatedStoresStoreNumberBranchesBranchNumberEditRoute: typeof AuthenticatedStoresStoreNumberBranchesBranchNumberEditRoute
  AuthenticatedStoresStoreNumberBranchesBranchNumberIndexRoute: typeof AuthenticatedStoresStoreNumberBranchesBranchNumberIndexRoute
  AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsCreateRoute: typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsCreateRoute
  AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberEditRoute: typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberEditRoute
  AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberIndexRoute: typeof AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTestRoute: AuthenticatedTestRoute,
  AuthenticatedStoresCreateRoute: AuthenticatedStoresCreateRoute,
  AuthenticatedStoresStoreNumberEditRoute:
    AuthenticatedStoresStoreNumberEditRoute,
  AuthenticatedStoresStoreNumberIndexRoute:
    AuthenticatedStoresStoreNumberIndexRoute,
  AuthenticatedStoresStoreNumberBranchesCreateRoute:
    AuthenticatedStoresStoreNumberBranchesCreateRoute,
  AuthenticatedStoresStoreNumberBranchesBranchNumberEditRoute:
    AuthenticatedStoresStoreNumberBranchesBranchNumberEditRoute,
  AuthenticatedStoresStoreNumberBranchesBranchNumberIndexRoute:
    AuthenticatedStoresStoreNumberBranchesBranchNumberIndexRoute,
  AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsCreateRoute:
    AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsCreateRoute,
  AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberEditRoute:
    AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberEditRoute,
  AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberIndexRoute:
    AuthenticatedStoresStoreNumberBranchesBranchNumberRoomsRoomNumberIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
