/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStoresCreateRouteImport } from './routes/_authenticated/stores/create'
import { Route as AuthenticatedStoresStoreIdIndexRouteImport } from './routes/_authenticated/stores/$storeId/index'
import { Route as AuthenticatedStoresStoreIdEditRouteImport } from './routes/_authenticated/stores/$storeId/edit'
import { Route as AuthenticatedStoresStoreIdBranchesCreateRouteImport } from './routes/_authenticated/stores/$storeId/branches/create'
import { Route as AuthenticatedStoresStoreIdBranchesBranchIdIndexRouteImport } from './routes/_authenticated/stores/$storeId/branches/$branchId/index'
import { Route as AuthenticatedStoresStoreIdBranchesBranchIdEditRouteImport } from './routes/_authenticated/stores/$storeId/branches/$branchId/edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoresCreateRoute =
  AuthenticatedStoresCreateRouteImport.update({
    id: '/stores/create',
    path: '/stores/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreIdIndexRoute =
  AuthenticatedStoresStoreIdIndexRouteImport.update({
    id: '/stores/$storeId/',
    path: '/stores/$storeId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreIdEditRoute =
  AuthenticatedStoresStoreIdEditRouteImport.update({
    id: '/stores/$storeId/edit',
    path: '/stores/$storeId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreIdBranchesCreateRoute =
  AuthenticatedStoresStoreIdBranchesCreateRouteImport.update({
    id: '/stores/$storeId/branches/create',
    path: '/stores/$storeId/branches/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreIdBranchesBranchIdIndexRoute =
  AuthenticatedStoresStoreIdBranchesBranchIdIndexRouteImport.update({
    id: '/stores/$storeId/branches/$branchId/',
    path: '/stores/$storeId/branches/$branchId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreIdBranchesBranchIdEditRoute =
  AuthenticatedStoresStoreIdBranchesBranchIdEditRouteImport.update({
    id: '/stores/$storeId/branches/$branchId/edit',
    path: '/stores/$storeId/branches/$branchId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/test': typeof AuthenticatedTestRoute
  '/admin/login': typeof AdminLoginRoute
  '/stores/create': typeof AuthenticatedStoresCreateRoute
  '/stores/$storeId/edit': typeof AuthenticatedStoresStoreIdEditRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdIndexRoute
  '/stores/$storeId/branches/create': typeof AuthenticatedStoresStoreIdBranchesCreateRoute
  '/stores/$storeId/branches/$branchId/edit': typeof AuthenticatedStoresStoreIdBranchesBranchIdEditRoute
  '/stores/$storeId/branches/$branchId': typeof AuthenticatedStoresStoreIdBranchesBranchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/test': typeof AuthenticatedTestRoute
  '/admin/login': typeof AdminLoginRoute
  '/stores/create': typeof AuthenticatedStoresCreateRoute
  '/stores/$storeId/edit': typeof AuthenticatedStoresStoreIdEditRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdIndexRoute
  '/stores/$storeId/branches/create': typeof AuthenticatedStoresStoreIdBranchesCreateRoute
  '/stores/$storeId/branches/$branchId/edit': typeof AuthenticatedStoresStoreIdBranchesBranchIdEditRoute
  '/stores/$storeId/branches/$branchId': typeof AuthenticatedStoresStoreIdBranchesBranchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/stores/create': typeof AuthenticatedStoresCreateRoute
  '/_authenticated/stores/$storeId/edit': typeof AuthenticatedStoresStoreIdEditRoute
  '/_authenticated/stores/$storeId/': typeof AuthenticatedStoresStoreIdIndexRoute
  '/_authenticated/stores/$storeId/branches/create': typeof AuthenticatedStoresStoreIdBranchesCreateRoute
  '/_authenticated/stores/$storeId/branches/$branchId/edit': typeof AuthenticatedStoresStoreIdBranchesBranchIdEditRoute
  '/_authenticated/stores/$storeId/branches/$branchId/': typeof AuthenticatedStoresStoreIdBranchesBranchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/test'
    | '/admin/login'
    | '/stores/create'
    | '/stores/$storeId/edit'
    | '/stores/$storeId'
    | '/stores/$storeId/branches/create'
    | '/stores/$storeId/branches/$branchId/edit'
    | '/stores/$storeId/branches/$branchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/test'
    | '/admin/login'
    | '/stores/create'
    | '/stores/$storeId/edit'
    | '/stores/$storeId'
    | '/stores/$storeId/branches/create'
    | '/stores/$storeId/branches/$branchId/edit'
    | '/stores/$storeId/branches/$branchId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/test'
    | '/admin/login'
    | '/_authenticated/stores/create'
    | '/_authenticated/stores/$storeId/edit'
    | '/_authenticated/stores/$storeId/'
    | '/_authenticated/stores/$storeId/branches/create'
    | '/_authenticated/stores/$storeId/branches/$branchId/edit'
    | '/_authenticated/stores/$storeId/branches/$branchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/create': {
      id: '/_authenticated/stores/create'
      path: '/stores/create'
      fullPath: '/stores/create'
      preLoaderRoute: typeof AuthenticatedStoresCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeId/': {
      id: '/_authenticated/stores/$storeId/'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeId/edit': {
      id: '/_authenticated/stores/$storeId/edit'
      path: '/stores/$storeId/edit'
      fullPath: '/stores/$storeId/edit'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeId/branches/create': {
      id: '/_authenticated/stores/$storeId/branches/create'
      path: '/stores/$storeId/branches/create'
      fullPath: '/stores/$storeId/branches/create'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdBranchesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeId/branches/$branchId/': {
      id: '/_authenticated/stores/$storeId/branches/$branchId/'
      path: '/stores/$storeId/branches/$branchId'
      fullPath: '/stores/$storeId/branches/$branchId'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdBranchesBranchIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeId/branches/$branchId/edit': {
      id: '/_authenticated/stores/$storeId/branches/$branchId/edit'
      path: '/stores/$storeId/branches/$branchId/edit'
      fullPath: '/stores/$storeId/branches/$branchId/edit'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdBranchesBranchIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
  AuthenticatedStoresCreateRoute: typeof AuthenticatedStoresCreateRoute
  AuthenticatedStoresStoreIdEditRoute: typeof AuthenticatedStoresStoreIdEditRoute
  AuthenticatedStoresStoreIdIndexRoute: typeof AuthenticatedStoresStoreIdIndexRoute
  AuthenticatedStoresStoreIdBranchesCreateRoute: typeof AuthenticatedStoresStoreIdBranchesCreateRoute
  AuthenticatedStoresStoreIdBranchesBranchIdEditRoute: typeof AuthenticatedStoresStoreIdBranchesBranchIdEditRoute
  AuthenticatedStoresStoreIdBranchesBranchIdIndexRoute: typeof AuthenticatedStoresStoreIdBranchesBranchIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTestRoute: AuthenticatedTestRoute,
  AuthenticatedStoresCreateRoute: AuthenticatedStoresCreateRoute,
  AuthenticatedStoresStoreIdEditRoute: AuthenticatedStoresStoreIdEditRoute,
  AuthenticatedStoresStoreIdIndexRoute: AuthenticatedStoresStoreIdIndexRoute,
  AuthenticatedStoresStoreIdBranchesCreateRoute:
    AuthenticatedStoresStoreIdBranchesCreateRoute,
  AuthenticatedStoresStoreIdBranchesBranchIdEditRoute:
    AuthenticatedStoresStoreIdBranchesBranchIdEditRoute,
  AuthenticatedStoresStoreIdBranchesBranchIdIndexRoute:
    AuthenticatedStoresStoreIdBranchesBranchIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
